default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  username: root
  password:
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: mchpwpush_development

test:
  <<: *default
  database: mchpwpush_test

production:
  <<: *default
  database: mchpwpush_production